[build]
publish = "dist"
command = "yarn build"

# == Headers ==
[[headers]]
for = "/*"

[headers.values]
x-frame-options = "deny"
x-xss-protection = "1; mode=block"

# Cache control headers.
[[headers]]
for = "/js/*"
cache-control = '''
max-age=31557600,
public'''

# Cache control headers.
[[headers]]
for = "/css/*"
cache-control = '''
max-age=31557600,
public'''

# Cache control headers.
[[headers]]
for = "/img/*"
cache-control = '''
max-age=31557600,
public'''

# == Redirects ==
[[redirects]]
from = "/resume"
to = "https://resume.stevenxie.me"
status = 200
